POST  http://localhost:3000/users/register  HTTP/1.1
Content-Type: application/json

{
  "username": "tor",
  "email": "tors@gmai.com",
  "password": "tor123"
 

}



###
POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "tors@gmai.com",
  "password": "tor123"
}


GET  http://localhost:3000/todo/670becd4d1940a3e6b700ac6  HTTP/1.1
Content-Type: application/json


{
    "title": "d",
    "description": "nest es un framewort de node "
}
###
GET  http://localhost:3000/todo  HTTP/1.1
Content-Type: application/json


{
    "title": "d",
    "description": "nest es un framewort de node "
}
###
PUT  http://localhost:3000/todo/670d358bb0b1194669b5c36c  HTTP/1.1
Content-Type: application/json


{
    
    "title": "what is nest",
    "description": "for make pages completed "
}

###
DELETE  http://localhost:3000/todo/670d358bb0b1194669b5c36c  HTTP/1.1
Content-Type: application/json
